import Head from 'next/head';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home(data) {
  const {posts}  = data;
  
 
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.grid}>
        {posts.map((post) => (
          <div key={post.node.slug} className={styles.card}>
            <div>
              <Link href={post.node.link}   aria-hidden="true" class="aal_anchor" id="country-name">
              {post.node.title}
              </Link>
             </div>
          </div>
        ))}
      </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
    query NewQuery {
      posts {
        edges {
          node {
            title
            slug
            link
          }
        }
      }
    }
    `,
  });

  return {
    props: {
      posts: data.posts.edges,
    },
 };
}